"""add password_hash to users

Revision ID: 0d25af489f39
Revises: d050d20c7cd4
Create Date: 2026-09-25 07:57:23.828721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d25af489f39'
down_revision: Union[str, None] = 'd050d20c7cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL with no server_default is safe here only because the users
    # table has never had any rows (nothing wrote to it before real
    # per-user auth existed - see README.md "User authentication"). This
    # would need a server_default (or a two-step backfill-then-constrain
    # migration) on a table that already had real user rows.
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
