"""initial schema: users, url_analysis, threat_intelligence, audit_logs

Revision ID: d050d20c7cd4
Revises: 
Create Date: 2026-09-25 12:00:16.006805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd050d20c7cd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('url_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_analysis_analyzed_at'), 'url_analysis', ['analyzed_at'], unique=False)
    op.create_index('ix_url_analysis_url', 'url_analysis', ['url'], unique=False)
    op.create_index('ix_url_analysis_user_analyzed_at', 'url_analysis', ['user_id', 'analyzed_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('anchored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['url_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_analysis_id'), 'audit_logs', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tx_hash'), 'audit_logs', ['tx_hash'], unique=False)
    op.create_table('threat_intelligence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['url_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_analysis_id'), 'threat_intelligence', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_intelligence_analysis_id'), table_name='threat_intelligence')
    op.drop_table('threat_intelligence')
    op.drop_index(op.f('ix_audit_logs_tx_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_analysis_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_url_analysis_user_analyzed_at', table_name='url_analysis')
    op.drop_index('ix_url_analysis_url', table_name='url_analysis')
    op.drop_index(op.f('ix_url_analysis_analyzed_at'), table_name='url_analysis')
    op.drop_table('url_analysis')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
