// Sample URLs for demos and the "Load sample data" button. They are run
// through the demo engine like any other scan (with back-dated timestamps),
// and are tagged source: 'sample' so they are never mistaken for real scans.
// Reserved/documentation IP ranges and invented domains only.

export const EXAMPLE_URLS = [
  { label: 'Phishing lure', url: 'http://secure-paypa1-login.com/verify-account?session=8841' },
  { label: 'Malware drop', url: 'http://203.0.113.45:8080/files/invoice_2026.exe' },
  { label: 'Shortened link', url: 'https://bit.ly/3xY7kQz' },
  { label: 'Legitimate site', url: 'https://github.com/Consoder/SKIT-CS-2023-2027-28' },
];

export const SAMPLE_URLS = [
  'https://www.google.com/search?q=url+security',
  'https://github.com/features/actions',
  'https://en.wikipedia.org/wiki/Phishing',
  'https://stackoverflow.com/questions/tagged/fastapi',
  'https://www.python.org/downloads/',
  'https://react.dev/learn',
  'https://www.skit.ac.in/',
  'https://docs.npmjs.com/cli',
  'https://www.linkedin.com/feed/',
  'https://www.amazon.in/gp/cart/view.html',
  'https://www.microsoft.com/en-in/windows',
  'https://developer.mozilla.org/en-US/docs/Web',
  'https://news.ycombinator.example.org/item?id=4412',
  'https://blog.acme-widgets.io/release-notes',
  'https://portfolio-diya.netlify.app/',
  'http://secure-paypa1-login.com/verify-account?session=8841',
  'http://appleid.apple.com.verify-user.tk/signin',
  'https://amaz0n-giftcard-reward.xyz/claim?user=winner',
  'http://netflix-billing-update.ga/account/suspended',
  'https://login.microsoftonline.com.office365-auth.ml/oauth2/authorize',
  'http://hdfc-netbanking-kyc.top/update-kyc.php',
  'http://secure.chase.account-verify.cf/logon',
  'http://user@paypal.com@198.51.100.77/webscr?cmd=login',
  'https://xn--pypal-4ve.com/signin',
  'http://binance-wallet-unlock.click/recover?next=https://binance.com',
  'http://203.0.113.45:8080/files/invoice_2026.exe',
  'http://198.51.100.23/bins/mirai.arm7.sh',
  'http://free-software-crack.xyz/download/keygen_setup.zip',
  'http://update-flash-player.gq/install/flashplayer.msi',
  'http://cdn-qx7v9kz2wpl.top/payload/stage2.bin',
  'http://192.0.2.10:4444/apk/whatsapp_gold.apk',
  'https://bit.ly/3xY7kQz',
  'https://tinyurl.com/yc8m4k2p',
  'http://promo-deals-online.shop/offer?utm_source=sms',
  'https://track.example-mailer.net/c/redirect?url=http%3A%2F%2Funknown-host.info',
  'http://my-cloud-storage-share.work/folder/8812',
  'http://cheap-meds-247.icu/buy',
  'https://files-share.xyz/d/Q2hlY2tsaXN0',
  'http://old-forum.example.com:8081/index.php?topic=52..%2F..%2Fetc',
  'https://survey-rewards.buzz/win?id=77',
];
